### ISSUE TITLE
Ryde

### ISSUE THREAD

**Issue by stevage** [stevage/OpenTrees#1]
http://data.nsw.gov.au/data/dataset/public-trees-2013

**Comment by andrewharvey** [comment]
what am I missing, Ryde doesn't show up in https://github.com/stevage/OpenTrees/blob/gh-pages/datasrc/sources.json but does show up at http://www.opentrees.org/

**Comment by stevage** [comment]
Looks like I probably got half way through this, generated the vector tiles but didn't push the code change. I was also trying to migrate away from using PostGIS to Spatialite and got a bit stuck, so it's probably wrapped up with that.
