### ISSUE TITLE
Import: Amsterdam, The Netherlands

### ISSUE THREAD

**Issue by gerwitz** [stevage/OpenTrees#10]
214k records across four downloads.

https://maps.amsterdam.nl/open_geodata/?k=254
https://maps.amsterdam.nl/open_geodata/?k=255
https://maps.amsterdam.nl/open_geodata/?k=256
https://maps.amsterdam.nl/open_geodata/?k=257

Rough translation of field names (I am not a native Dutch speaker):

`Soortnaam_NL`: species name in Dutch
`Boomnummer`: Tree number
`Soortnaam_WTS`: species name in English?
`Boomtype`: Planting type
`Boomhoogte`: height (range, in meters)
`Plantjaar`: year planted
`Eigenaar`: owner
`Beheerder`: caretaker
`Categorie`: ?
`SOORT_KORT`: species short name
`SDVIEW`: ?
`RADIUS`: rendering radius

**Comment by stevage** [comment]
![Screen Shot 2020-03-06 at 12 33 14 pm](https://user-images.githubusercontent.com/678344/76041603-affc9f80-5fa6-11ea-8f44-347c81e86e82.png)

Thanks! WIP - will be deployed soon.
