### ISSUE TITLE
Import - Wesel 

### ISSUE THREAD

**Issue by j-lippmann** [stevage/OpenTrees#11]
Can You please import:

City: Wesel
http://data.geoportal-wesel.de/OPENDATA/Baumkataster/Baumkataster.geojson

Columnmatching:
scientific = GA_LANG -- hint: "lat. name, german name"
height = BAUMHOEHE
crown = KR_DURCHM
dbh = ST_UMFANG

Thanks and Greetings
Jan

Website: https://open.nrw/dataset/baumkataster-odp

**Comment by stevage** [comment]
![Screen Shot 2020-03-08 at 10 23 32 am](https://user-images.githubusercontent.com/678344/76153876-0264ca00-6127-11ea-87f0-a722b5d6ad1f.png)

Thank you, will be uploaded soon.
