### ISSUE TITLE
[Add source] -Linz

### ISSUE THREAD

**Issue by j-lippmann** [stevage/OpenTrees#13]
* Name of town/city/whatever:Linz
* Page with information about the dataset:https://www.data.gv.at/katalog/dataset/baumkataster
* URL that directly downloads the dataset:http://data.linz.gv.at/katalog/umwelt/baumkataster/2020/FME_BaumdatenBearbeitet_OGD_20200225.csv
* Dataset format (should be CSV, GeoJSON or zipped Shapefile): 
* Country: Austria
* Important fields (if not in English/French - especially height, diameter, crown width):

tree number:BaumNr
scientific: Gattung + Art
kind: Sorte
common name: NameDeutsch
height:Hoehe
crown: Schirmdurchmesser
dbh:Stammumfang

Thanks! :-)

**Comment by stevage** [comment]
![Screen Shot 2020-03-08 at 10 01 10 pm](https://user-images.githubusercontent.com/678344/76161526-581d8e80-6188-11ea-873c-e06bd4e3823f.png)

Thanks, will be available soon.
