### ISSUE TITLE
[Add source] Ulm

### ISSUE THREAD

**Issue by looniverse** [stevage/OpenTrees#19]
>Note: we only want databases that are:

>* the product of on-the-ground tree surveying (not aerial imagery), 
>* open data
>* not duplicating another source of data already included

* Name of town/city/whatever: Ulm
* Page with information about the dataset: http://www.daten.ulm.de/datenkatalog/metadaten/baumbestand-stadt-ulm-testdatensatz
* URL that directly downloads the dataset: http://daten.ulm.de/sites/default/files/20180921_Baeume_1.xlsx
* Dataset format (should be CSV, GeoJSON or zipped Shapefile): xlsx
* Country: Germany
* Important fields (if not in English/French - especially height, diameter, crown width):
Coords are in GK3; Baumart_botanisch: species; Baumhöhe_(aktuell): height; Kronendurchm_(aktuell): crown width; Stammdurchm_(aktuell): diameter

**Comment by stevage** [comment]
Thank you! Now included on opentrees.org.
