### ISSUE TITLE
Berlin/Germany

### ISSUE THREAD

**Issue by derbuerger** [stevage/OpenTrees#20]
* Name of town/city/whatever: Berlin
* Page with information about the dataset: [](https://fbinter.stadt-berlin.de/fb/index.jsp)
* URL that directly downloads the dataset: https://fbinter.stadt-berlin.de/fb/wfs/data/senstadt/s_wfs_baumbestand
* Dataset format (should be CSV, GeoJSON or zipped Shapefile): WFS
* Country: Germany
* Important fields (if not in English/French - especially height, diameter, crown width):
crown width=KRONEDURCH
height=Baumhoehe

need more translation? 

licence note: "Geoportal Berlin / Baumbestand Berlin".

**Comment by stevage** [comment]
Berlin is already included?

<img width="832" alt="Screen Shot 2020-03-11 at 4 32 40 pm" src="https://user-images.githubusercontent.com/678344/76385505-f2aee500-63b5-11ea-933b-3a5648d1306a.png">
