### ISSUE TITLE
[Add source] Antwerpen (Belgium)

### ISSUE THREAD

**Issue by mstuyts** [stevage/OpenTrees#21]
* Name of city: Antwerpen
* Page with information about the dataset: https://portaal-stadantwerpen.opendata.arcgis.com/datasets/boom/data
* URL that directly downloads the dataset: https://opendata.arcgis.com/datasets/0293af55ca454b44ba789ee14c82543a_676.zip or https://opendata.arcgis.com/datasets/0293af55ca454b44ba789ee14c82543a_676.geojson
* Dataset format (should be CSV, GeoJSON or zipped Shapefile): zipped Shapefile or GeoJSON
* Country: Belgium
* Important fields (if not in English/French - especially height, diameter, crown width):
    * LATBOOMSOO: Scientific name
    * STAMOMTREK: diameter

**Comment by stevage** [comment]
Thank you! Now included on opentrees.org.
