### ISSUE TITLE
Valencia, Spain

### ISSUE THREAD

**Issue by jsanz** [stevage/OpenTrees#29]
* Name of town/city/whatever: Valencia
* Page with information about the dataset: http://gobiernoabierto.valencia.es/en/dataset/?id=arbolado (in Spanish)
* URL that directly downloads the dataset: http://mapas.valencia.es/lanzadera/opendata/arboles/JSON
* Dataset format (should be CSV, GeoJSON or zipped Shapefile): GeoJSON
* Country: Spain
* Important fields (if not in English/French - especially height, diameter, crown width): the most relevant field is `planta` with the Latin species name.
* License: [CC By 4.0](http://gobiernoabierto.valencia.es/en/terms-reuse)

**Comment by stevage** [comment]
Done, thank you!
