### ISSUE TITLE
Oakland, CA, USA

### ISSUE THREAD

**Issue by timoha** [stevage/OpenTrees#37]
* Name of city: Oakland, CA
* Page with information about the dataset: https://data.oaklandnet.com/Environmental/Oakland-Street-Trees/4jcx-enxf
* URL that directly downloads the dataset:
  - https://data.oaklandnet.com/resource/4jcx-enxf.json
  - https://data.oaklandnet.com/resource/4jcx-enxf.geojson
  - https://data.oaklandnet.com/resource/4jcx-enxf.csv
* Dataset format: JSON, GeoJSON, CSV
* Country: USA
* Important fields (if not in English/French - especially height, diameter, crown width):
  - wellwidth
  - welllength
  - pareawidth
  - lowwell
  - species
  - location_1

**Comment by stevage** [comment]
I have been tricked by this dataset before. All the latitudes/longitudes are just the centroid of Oakland. No actual spatial information here. (The geojson one doesn't even have geometry).

**Comment by timoha** [comment]
my bad, I assumed that [this map](https://data.oaklandnet.com/dataset/Street-Trees/9e7e-63pp) was using the data I referenced. It appears that the map can also be exported as same formats. However, I don't seem to find the original source of data.
