### ISSUE TITLE
Import: "Bäume (Ausspielung Baumkataster) Halle (Saale) in Germany"

### ISSUE THREAD

**Issue by geoObserver** [stevage/OpenTrees#6]
Please import the OpenData-Set of trees from Halle (Saale) in Germany. The dataset ist open at: https://www.halle.de/de/Verwaltung/Online-Angebote/Offene-Verwaltungsdaten/Mit-Kartenbezug/index.aspx?ID=f2087a53-2c10-f7c5-4dba-9ad5112a90cb

THX, mikeE., the #geoObserver

**Comment by stevage** [comment]
Will be online soon.
