### ISSUE TITLE
Import: "Straßenbäume (Berlin)" and "Anlagenbäume (Berlin)"

### ISSUE THREAD

**Issue by Adarkas2302** [stevage/OpenTrees#7]
Please import the datasets "Baumbestand Berlin - Straßenbäume" and "Baumbestand Berlin - Anlagenbäume" they are open at:

https://fbinter.stadt-berlin.de/fb/berlin/service_intern.jsp?id=s_wfs_baumbestand_an@senstadt&type=WFS
and
https://fbinter.stadt-berlin.de/fb/berlin/service_intern.jsp?id=s_wfs_baumbestand@senstadt&type=WFS

Columnmatching:
ref = KENNZEICH
scientific = ART_BOT
height = BAUMHOEHE
crown = KRONEDRUCH
dbh = STAMMUMFG
planted = PFLANZJAHR
location = NAMENR

If you need any other column infos, just ask.

thx, Adarkas

**Comment by stevage** [comment]
Do you have a direct URL for the actual download? I already tried with Berlin a couple of times and kept running into an issue where it said my requset was too large. (Well, I think it said that...:))

**Comment by Adarkas2302** [comment]
Try it with those links:
https://fbinter.stadt-berlin.de/fb/wfs/data/senstadt/s_wfs_baumbestand_an
and
https://fbinter.stadt-berlin.de/fb/wfs/data/senstadt/s_wfs_baumbestand

I used those links in QGIS and they work.

**Comment by stevage** [comment]
It's ok I found a better source.

**Comment by Adarkas2302** [comment]
Witch one are you using now? If you don't mind me asking?

**Comment by stevage** [comment]
https://opendata.arcgis.com/datasets/05c3f9d7dea6422b86e30967811bddd7_0.zip

**Comment by Adarkas2302** [comment]
Thanks, I already saw the trees in the map.
