### ISSUE TITLE
Import: Kelowna, BC, Canada

### ISSUE THREAD

**Issue by dgoodlad** [stevage/OpenTrees#9]
Kelowna seems to have a large tree database here: http://opendata.kelowna.ca/datasets/39d13a47b8f94cce82a9b4c86efc8ee7/data?geometry=-119.693%2C49.577%2C-119.178%2C49.887 

A direct download link for the entire dataset of some 23k trees as a shapefile is here:

https://opendata.arcgis.com/datasets/39d13a47b8f94cce82a9b4c86efc8ee7_114.zip?outSR=26911

**Comment by stevage** [comment]
Done!
